server:
  port: 8764
spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://config-service:8763
      username: lewis
      password: 111111
      fail-fast: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  config-location:
  mapper-locations: "classpath*:mapper/*.xml"
